### ISSUE TITLE
缺少lib文件夹

### ISSUE THREAD

**Issue by mxpasser** [YAANNZ/XiaKeCaiBangBang#3]
下载了zip文件，缺少文件：
ld: warning: directory not found for option '~~/XiaKeCaiBangBang-master/XiaKeCBB/Classes/Main/Lib/EaseMobSDK/lib'
ld: library not found for -lEaseMobClientSDK

**Comment by YAANNZ** [comment]
pod 一下就好了，上传上来太麻烦
